
notifications:
  email: false
git:
  submodules: false


language:
  node_js
node_js:
  -  8.6
sudo: false
addons:
  apt:
    packages:
      - wget
      - zip


install:
  - npm install -g codecov
  - npm install
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
