
notifications:
  email: false
git:
  submodules: false


language:
  node_js
sudo: false
addons:
  apt:
    packages:
      - wget
      - zip


install:
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
