
notifications:
  email: false
git:
  submodules: false


language:
  node_js
node_js:
  -  8.6
sudo: false
addons:
  apt:
    packages:
      - wget
      - zip


install:
  - npm install
script:
  - npm test
  - codecov
